# importing the relevant libraries

In [1]:
import numpy as np

# scalars

In [2]:
s = 13

In [3]:
s

13

# vectors

In [4]:
v = np.array([5,-2,3])
v

array([ 5, -2,  3])

In [9]:
v.shape

(3,)

In [10]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 3]])

# matrix

In [6]:
m = np.array([[5,6,8],[21,4,5]])
m

array([[ 5,  6,  8],
       [21,  4,  5]])

In [11]:
m.shape

(2, 3)

# tensor

In [21]:
m2 = np.array([[1,3,4],[4,3,23]])
m2

array([[ 1,  3,  4],
       [ 4,  3, 23]])

In [21]:
t = np.array([m,m2])
t

array([[[ 5,  6,  8],
        [21,  4,  5]],

       [[ 1,  3,  4],
        [ 4,  3, 23]]])

In [22]:
t.shape

(2, 2, 3)

# mannually creating the tesnor 

In [25]:
t1 = np.array([[[2,3,4],[2,3,1],[4,3,2],[1,4,5]]])
t1

array([[[2, 3, 4],
        [2, 3, 1],
        [4, 3, 2],
        [1, 4, 5]]])

In [26]:
t.shape

(2, 2, 3)

# transposing the matrix

In [22]:
a = np.array([[1,2],[4,6],[3,2]])
a

array([[1, 2],
       [4, 6],
       [3, 2]])

In [3]:
a.T

array([[1, 4],
       [2, 6],
       [3, 2]])

# transposing scalars

In [4]:
a = np.array([5])
a.T

array([5])

# transposing vectors

In [5]:
x = np.array([1,2,3])
x.T

array([1, 2, 3])

In [10]:
x_reshaped= x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [9]:
x_reshaped.T

array([[1],
       [2],
       [3]])

# dot product vectors 

In [11]:
x = np.array([3,5,6])
y= np.array([4,5,2])
np.dot(x,y)

49

# scalar * sacalar

In [12]:
np.dot(5,4)

20

In [13]:
np.dot(-2,4)

-8

# scalar * vector

In [14]:
x

array([3, 5, 6])

In [15]:
5*x

array([15, 25, 30])

# scalar * matrix 

In [19]:
a

array([[1, 2, 3],
       [4, 6, 2]])

In [20]:
5*a

array([[ 5, 10, 15],
       [20, 30, 10]])

 # matrix * matrix 

In [23]:
np.dot(a,m2)

array([[  9,   9,  50],
       [ 28,  30, 154],
       [ 11,  15,  58]])